version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=127.0.0.1
      - DB_PORT=5432
      - DB_DATABASE=vehiculo-crud
      - DB_USERNAME=postgres
      - DB_PASSWORD= Alexander150
    command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: postgres:latest
    container_name: laravel-db
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Alexander150
      POSTGRES_DB: vehiculo-crud
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: