services:
   name: backend
    type: web 
    runtime: php 8.2
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan migrate --force
    startCommand: |
      php artisan serve --host 0.0.0.0 --port 10000
    env:
      DB_CONNECTION: pgsql
      DB_HOST: dpg-ctfk9d52ng1s738ki870-a 
      DB_PORT: 5432
      DB_DATABASE: examen1_0
      DB_USERNAME: examen1_0_user
      DB_PASSWORD: repZYLN5V8dZDCSOnFbxR6JYi8RCOKeP
